# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "KsquXSoWdS2w98JX3vIszcjFUH223qa0JON436AaKCwfoCQ/nu/Qw1gSlgat7NrtU47ItKZPWjVEUhIbls5wihCSlvpCrZ3mTdaAcNHCQAK+EgCgo327vFPwK9G1hPGyCVLvi+xnk1vqKm3ianrWJiXodttPoqnHhhUcFVSJ53bl6aqf5AjdYJb0nlHRFfUiFMnBZBP6PtCUGhFmq5SpBeTYH8j621Xml+B3oOxJIfYWt3B5tZiZku1L7PexmJ3hSGHgNtgCQE3PTmVcCloUs4tR90iqOldb3uWhA6WjqMEliqgHy+ItaN+Orw1kG+aupUK8bEMLQ72rCXj/iRHgFTWRSLDJMVM3GnuaNZPRMa+mQs8qt8bojZ1snk4KsmE7bD+lIpSzC7GpEqbu/+tWlJRjbFLmiu4yyyXr2DSHuAdvKPlC8W+npsv1kKIw+MFCyDAfgbL/ryelE0SvPw0vswAkzFi9YX4A+6yMcpiWsl2euDEaE6BctXBnaKEi0XVs+hPCs4dvYzUULsHXRaaEqOQbZFXY8dbfuL4mTeua0NaA2OVwn2TEydlEU8EuSHJlgZEjMg99FDk3elsIhKLZr8Vu+ekOfLUqZej0Ayd//So7OUY6dyL+KEwUNLOf8YhZIxV8qIUP4xdRYa1Uk55vpn1DoRttAzRpe9kLj4QJOdU="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
