travis:
  secure:
    BINSTAR_TOKEN: hTDklVYLlkTGpa2x6Ss7rcKZwgUiqg2hPFV+fOXppMaZjmgVpbpKF6koakebChimCKg4qtbs7c9SNZNpeKEVBMnYg77aY8kmS13jksjXfyEBQrihghoWPREywVvPpvx/y5otGrDD+mOgtc6d8u2bjX0UazT7PcE/mOssO+dPXUVrYJ8EmoidNIO7ABEPl/1OLSa09v4RUp1mBDQ0aZf4e8gS70I5C8U68Qsgz8t6Jvj9Dh3T3IwUGnINFbAiYhnTW+wvQcWo6FmggaUtvqrm+Qc/teQEI2R3Vi3PWiJz1YxrSkxecPC0aiC1lp3Yy0jChkeKiPpp1dG9boMs7O3/9uwqkUKvcK1N9PkRPtVrTjEcE7yyJC83DeTHJZbzETu15gNYquvH14bt/Y/utiEOjxGfumGq5VMQ+PsM6H0r8io/yT0AZmgPqKkG5IjtzgTQhBlRmwHfPSr5NXQu+cFhwtPdyVKHwwBfM1A/y8BcxpdbMrRa3huc3Lsmy24DQCrLGGjY9hjZlznO/ywxK4iTUXQiMAutzRTPfB4Bw1OECRUF3BCgMDAX5bY01T9CQIFlxJsdnqh9GF3WZ4cEwtBtq21bo8NoCNVZFcF6zwt3pbO0fVXiSqcdOhsP5y9S6U8OIB+CAVPbw9hc1L4hyPWuE7Wz3TVHm/wYh/iRF5mCSWg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
