travis:
  secure:
    BINSTAR_TOKEN: KsquXSoWdS2w98JX3vIszcjFUH223qa0JON436AaKCwfoCQ/nu/Qw1gSlgat7NrtU47ItKZPWjVEUhIbls5wihCSlvpCrZ3mTdaAcNHCQAK+EgCgo327vFPwK9G1hPGyCVLvi+xnk1vqKm3ianrWJiXodttPoqnHhhUcFVSJ53bl6aqf5AjdYJb0nlHRFfUiFMnBZBP6PtCUGhFmq5SpBeTYH8j621Xml+B3oOxJIfYWt3B5tZiZku1L7PexmJ3hSGHgNtgCQE3PTmVcCloUs4tR90iqOldb3uWhA6WjqMEliqgHy+ItaN+Orw1kG+aupUK8bEMLQ72rCXj/iRHgFTWRSLDJMVM3GnuaNZPRMa+mQs8qt8bojZ1snk4KsmE7bD+lIpSzC7GpEqbu/+tWlJRjbFLmiu4yyyXr2DSHuAdvKPlC8W+npsv1kKIw+MFCyDAfgbL/ryelE0SvPw0vswAkzFi9YX4A+6yMcpiWsl2euDEaE6BctXBnaKEi0XVs+hPCs4dvYzUULsHXRaaEqOQbZFXY8dbfuL4mTeua0NaA2OVwn2TEydlEU8EuSHJlgZEjMg99FDk3elsIhKLZr8Vu+ekOfLUqZej0Ayd//So7OUY6dyL+KEwUNLOf8YhZIxV8qIUP4xdRYa1Uk55vpn1DoRttAzRpe9kLj4QJOdU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
